#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EggLotteryDataManager

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EggLotteryDataManager.BP_EggLotteryDataManager_C
// 0x00B0 (0x0340 - 0x0290)
class ABP_EggLotteryDataManager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, class UEggLotteryDataHolder_C*> PalEggLotteryMap;                                  // 0x02A0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<EPalElementType, class FName>            EggElementMap;                                     // 0x02F0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void SetupPalEggLotteryData();
	void ReceiveBeginPlay();
	class FName GetRandomEggPal(class FName EggId);
	void GetEggFromElement(EPalElementType ElementType, class FName* Value);
	void ExecuteUbergraph_BP_EggLotteryDataManager(int32 EntryPoint);
	void AddPalEggLotteryDataEntry(class FName EggId, class FName CharacterID);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EggLotteryDataManager_C">();
	}
	static class ABP_EggLotteryDataManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EggLotteryDataManager_C>();
	}
};
static_assert(alignof(ABP_EggLotteryDataManager_C) == 0x000008, "Wrong alignment on ABP_EggLotteryDataManager_C");
static_assert(sizeof(ABP_EggLotteryDataManager_C) == 0x000340, "Wrong size on ABP_EggLotteryDataManager_C");
static_assert(offsetof(ABP_EggLotteryDataManager_C, UberGraphFrame) == 0x000290, "Member 'ABP_EggLotteryDataManager_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_EggLotteryDataManager_C, DefaultSceneRoot) == 0x000298, "Member 'ABP_EggLotteryDataManager_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_EggLotteryDataManager_C, PalEggLotteryMap) == 0x0002A0, "Member 'ABP_EggLotteryDataManager_C::PalEggLotteryMap' has a wrong offset!");
static_assert(offsetof(ABP_EggLotteryDataManager_C, EggElementMap) == 0x0002F0, "Member 'ABP_EggLotteryDataManager_C::EggElementMap' has a wrong offset!");

}

