#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalInputData_XInput_WinGDK

#include "Basic.hpp"

#include "BP_PalInputData_XInput_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalInputData_XInput_WinGDK.BP_PalInputData_XInput_WinGDK_C
// 0x0000 (0x0110 - 0x0110)
class UBP_PalInputData_XInput_WinGDK_C final : public UBP_PalInputData_XInput_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PalInputData_XInput_WinGDK_C">();
	}
	static class UBP_PalInputData_XInput_WinGDK_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PalInputData_XInput_WinGDK_C>();
	}
};
static_assert(alignof(UBP_PalInputData_XInput_WinGDK_C) == 0x000008, "Wrong alignment on UBP_PalInputData_XInput_WinGDK_C");
static_assert(sizeof(UBP_PalInputData_XInput_WinGDK_C) == 0x000110, "Wrong size on UBP_PalInputData_XInput_WinGDK_C");

}

