#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalOilrigController_Debug

#include "Basic.hpp"

#include "BP_PalOilrigController_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalOilrigController_Debug.BP_PalOilrigController_Debug_C
// 0x0000 (0x0310 - 0x0310)
class ABP_PalOilrigController_Debug_C final : public ABP_PalOilrigController_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PalOilrigController_Debug_C">();
	}
	static class ABP_PalOilrigController_Debug_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PalOilrigController_Debug_C>();
	}
};
static_assert(alignof(ABP_PalOilrigController_Debug_C) == 0x000008, "Wrong alignment on ABP_PalOilrigController_Debug_C");
static_assert(sizeof(ABP_PalOilrigController_Debug_C) == 0x000310, "Wrong size on ABP_PalOilrigController_Debug_C");

}

