#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalCutsceneCamera

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "CinematicCamera_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalCutsceneCamera.BP_PalCutsceneCamera_C
// 0x0070 (0x0A90 - 0x0A20)
class ABP_PalCutsceneCamera_C final : public ACineCameraActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A20(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneCaptureComponent2D*               SceneCaptureComponent2D;                           // 0x0A28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TMap<EPalBossType, class UClass*>             BossDemoWidgetMap;                                 // 0x0A30(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UWBP_BossDemoBase_C*                    NowDisplayingBossDemoWidget;                       // 0x0A80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PalCutsceneCamera(int32 EntryPoint);
	void PreSetupBossDemoCapture();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);
	void StartCaptureBossDemo(EPalBossType BossType);
	void StopBossDemoCapture();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PalCutsceneCamera_C">();
	}
	static class ABP_PalCutsceneCamera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PalCutsceneCamera_C>();
	}
};
static_assert(alignof(ABP_PalCutsceneCamera_C) == 0x000010, "Wrong alignment on ABP_PalCutsceneCamera_C");
static_assert(sizeof(ABP_PalCutsceneCamera_C) == 0x000A90, "Wrong size on ABP_PalCutsceneCamera_C");
static_assert(offsetof(ABP_PalCutsceneCamera_C, UberGraphFrame) == 0x000A20, "Member 'ABP_PalCutsceneCamera_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_PalCutsceneCamera_C, SceneCaptureComponent2D) == 0x000A28, "Member 'ABP_PalCutsceneCamera_C::SceneCaptureComponent2D' has a wrong offset!");
static_assert(offsetof(ABP_PalCutsceneCamera_C, BossDemoWidgetMap) == 0x000A30, "Member 'ABP_PalCutsceneCamera_C::BossDemoWidgetMap' has a wrong offset!");
static_assert(offsetof(ABP_PalCutsceneCamera_C, NowDisplayingBossDemoWidget) == 0x000A80, "Member 'ABP_PalCutsceneCamera_C::NowDisplayingBossDemoWidget' has a wrong offset!");

}

