#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SnapModeFX

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_SnapModeFX.BP_SnapModeFX_C.ExecuteUbergraph_BP_SnapModeFX
// 0x0020 (0x0020 - 0x0000)
struct BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentScale_ReturnValue;         // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX) == 0x000008, "Wrong alignment on BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX");
static_assert(sizeof(BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX) == 0x000020, "Wrong size on BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX");
static_assert(offsetof(BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX, EntryPoint) == 0x000000, "Member 'BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX, CallFunc_K2_GetComponentScale_ReturnValue) == 0x000008, "Member 'BP_SnapModeFX_C_ExecuteUbergraph_BP_SnapModeFX::CallFunc_K2_GetComponentScale_ReturnValue' has a wrong offset!");

// Function BP_SnapModeFX.BP_SnapModeFX_C.Hide
// 0x0100 (0x0100 - 0x0000)
struct BP_SnapModeFX_C_Hide final
{
public:
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0018(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_SnapModeFX_C_Hide) == 0x000008, "Wrong alignment on BP_SnapModeFX_C_Hide");
static_assert(sizeof(BP_SnapModeFX_C_Hide) == 0x000100, "Wrong size on BP_SnapModeFX_C_Hide");
static_assert(offsetof(BP_SnapModeFX_C_Hide, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000000, "Member 'BP_SnapModeFX_C_Hide::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_Hide, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000018, "Member 'BP_SnapModeFX_C_Hide::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");

// Function BP_SnapModeFX.BP_SnapModeFX_C.ShowCenterSnap
// 0x0510 (0x0510 - 0x0000)
struct BP_SnapModeFX_C_ShowCenterSnap final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Rotation;                                          // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                BoxExtent;                                         // 0x0030(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                SnapStart;                                         // 0x0048(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                SnapEnd;                                           // 0x0060(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAttachWall;                                      // 0x0078(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x00B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_1;                // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0118(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_2;                 // 0x0130(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0148(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_K2_GetComponentScale_ReturnValue;         // 0x0230(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_2;                          // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_2;                          // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_2;                          // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_3;                          // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_3;                          // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_3;                          // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_3;                 // 0x0278(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue;           // 0x0290(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        CallFunc_BreakVector_X_4;                          // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_4;                          // 0x02B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_4;                          // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_Distance_ReturnValue;              // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult;       // 0x02C8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x03B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_2;        // 0x03C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_4;                 // 0x03C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x03E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x03F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x0410(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_Divide_VectorVector_ReturnValue;          // 0x04F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SnapModeFX_C_ShowCenterSnap) == 0x000008, "Wrong alignment on BP_SnapModeFX_C_ShowCenterSnap");
static_assert(sizeof(BP_SnapModeFX_C_ShowCenterSnap) == 0x000510, "Wrong size on BP_SnapModeFX_C_ShowCenterSnap");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, Location) == 0x000000, "Member 'BP_SnapModeFX_C_ShowCenterSnap::Location' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, Rotation) == 0x000018, "Member 'BP_SnapModeFX_C_ShowCenterSnap::Rotation' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, BoxExtent) == 0x000030, "Member 'BP_SnapModeFX_C_ShowCenterSnap::BoxExtent' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, SnapStart) == 0x000048, "Member 'BP_SnapModeFX_C_ShowCenterSnap::SnapStart' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, SnapEnd) == 0x000060, "Member 'BP_SnapModeFX_C_ShowCenterSnap::SnapEnd' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, IsAttachWall) == 0x000078, "Member 'BP_SnapModeFX_C_ShowCenterSnap::IsAttachWall' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000080, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_X) == 0x000098, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Y) == 0x0000A0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Z) == 0x0000A8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_MakeVector_ReturnValue) == 0x0000B0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0000C8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_X_1) == 0x0000E0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Y_1) == 0x0000E8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Z_1) == 0x0000F0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x0000F8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000100, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_SelectFloat_ReturnValue) == 0x000108, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_SelectFloat_ReturnValue_1) == 0x000110, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_SelectFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_MakeVector_ReturnValue_1) == 0x000118, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_MakeVector_ReturnValue_2) == 0x000130, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_MakeVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000148, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_K2_GetComponentScale_ReturnValue) == 0x000230, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_K2_GetComponentScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_X_2) == 0x000248, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_X_2' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Y_2) == 0x000250, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Y_2' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Z_2) == 0x000258, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Z_2' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_X_3) == 0x000260, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_X_3' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Y_3) == 0x000268, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Y_3' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Z_3) == 0x000270, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Z_3' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_MakeVector_ReturnValue_3) == 0x000278, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_MakeVector_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_FindLookAtRotation_ReturnValue) == 0x000290, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_FindLookAtRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_X_4) == 0x0002A8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_X_4' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Y_4) == 0x0002B0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Y_4' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_BreakVector_Z_4) == 0x0002B8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_BreakVector_Z_4' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Vector_Distance_ReturnValue) == 0x0002C0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Vector_Distance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_K2_SetWorldRotation_SweepHitResult) == 0x0002C8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_K2_SetWorldRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x0003B0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x0003B8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Divide_DoubleDouble_ReturnValue_2) == 0x0003C0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Divide_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_MakeVector_ReturnValue_4) == 0x0003C8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_MakeVector_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Add_VectorVector_ReturnValue) == 0x0003E0, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x0003F8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x000410, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowCenterSnap, CallFunc_Divide_VectorVector_ReturnValue) == 0x0004F8, "Member 'BP_SnapModeFX_C_ShowCenterSnap::CallFunc_Divide_VectorVector_ReturnValue' has a wrong offset!");

// Function BP_SnapModeFX.BP_SnapModeFX_C.ShowSnap
// 0x0178 (0x0178 - 0x0000)
struct BP_SnapModeFX_C_ShowSnap final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Rotation;                                          // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                BoxExtent;                                         // 0x0030(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0048(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x0078(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_Divide_VectorVector_ReturnValue;          // 0x0160(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SnapModeFX_C_ShowSnap) == 0x000008, "Wrong alignment on BP_SnapModeFX_C_ShowSnap");
static_assert(sizeof(BP_SnapModeFX_C_ShowSnap) == 0x000178, "Wrong size on BP_SnapModeFX_C_ShowSnap");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, Location) == 0x000000, "Member 'BP_SnapModeFX_C_ShowSnap::Location' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, Rotation) == 0x000018, "Member 'BP_SnapModeFX_C_ShowSnap::Rotation' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, BoxExtent) == 0x000030, "Member 'BP_SnapModeFX_C_ShowSnap::BoxExtent' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, CallFunc_Add_VectorVector_ReturnValue) == 0x000048, "Member 'BP_SnapModeFX_C_ShowSnap::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000060, "Member 'BP_SnapModeFX_C_ShowSnap::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x000078, "Member 'BP_SnapModeFX_C_ShowSnap::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_SnapModeFX_C_ShowSnap, CallFunc_Divide_VectorVector_ReturnValue) == 0x000160, "Member 'BP_SnapModeFX_C_ShowSnap::CallFunc_Divide_VectorVector_ReturnValue' has a wrong offset!");

}

