#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeMenu_ChararcterListEntry

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "CreativeMenu_CharacterStruct_structs.hpp"


namespace SDK::Params
{

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.SetSelected
// 0x0001 (0x0001 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_SetSelected final
{
public:
	bool                                          Param_IsSelected;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_SetSelected) == 0x000001, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_SetSelected");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_SetSelected) == 0x000001, "Wrong size on CreativeMenu_ChararcterListEntry_C_SetSelected");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_SetSelected, Param_IsSelected) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_SetSelected::Param_IsSelected' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.SetHighlighted
// 0x002C (0x002C - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_SetHighlighted final
{
public:
	bool                                          Param_IsHighlighted;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB1[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0004(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0018(0x0014)()
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_SetHighlighted) == 0x000004, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_SetHighlighted");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_SetHighlighted) == 0x00002C, "Wrong size on CreativeMenu_ChararcterListEntry_C_SetHighlighted");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_SetHighlighted, Param_IsHighlighted) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_SetHighlighted::Param_IsHighlighted' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_SetHighlighted, K2Node_MakeStruct_SlateColor) == 0x000004, "Member 'CreativeMenu_ChararcterListEntry_C_SetHighlighted::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_SetHighlighted, K2Node_MakeStruct_SlateColor_1) == 0x000018, "Member 'CreativeMenu_ChararcterListEntry_C_SetHighlighted::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.PrintToModLoader
// 0x0010 (0x0010 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_PrintToModLoader final
{
public:
	class FString                                 Message;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_PrintToModLoader) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_PrintToModLoader");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_PrintToModLoader) == 0x000010, "Wrong size on CreativeMenu_ChararcterListEntry_C_PrintToModLoader");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_PrintToModLoader, Message) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_PrintToModLoader::Message' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.OnUnhover__DelegateSignature
// 0x0058 (0x0058 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature final
{
public:
	struct FCreativeMenu_CharacterStruct          Data;                                              // 0x0000(0x0058)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature) == 0x000058, "Wrong size on CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature, Data) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_OnUnhover__DelegateSignature::Data' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.OnLoaded_107D8731494F973677EF5A94FA535FFC
// 0x0008 (0x0008 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC) == 0x000008, "Wrong size on CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC, Loaded) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_OnLoaded_107D8731494F973677EF5A94FA535FFC::Loaded' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet final
{
public:
	class UObject*                                ListItemObject;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet) == 0x000008, "Wrong size on CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet, ListItemObject) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_OnListItemObjectSet::ListItemObject' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.OnHover__DelegateSignature
// 0x0058 (0x0058 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature final
{
public:
	struct FCreativeMenu_CharacterStruct          Data;                                              // 0x0000(0x0058)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature) == 0x000058, "Wrong size on CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature, Data) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_OnHover__DelegateSignature::Data' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.OnClick__DelegateSignature
// 0x0058 (0x0058 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature final
{
public:
	struct FCreativeMenu_CharacterStruct          Data;                                              // 0x0000(0x0058)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature) == 0x000058, "Wrong size on CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature, Data) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_OnClick__DelegateSignature::Data' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.ExecuteUbergraph_CreativeMenu_ChararcterListEntry
// 0x00E8 (0x00E8 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB2[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB3[0x2];                                     // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0020(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsExpanded;                          // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSelected;                          // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB4[0x6];                                     // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_Event_ListItemObject;                       // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCreativeMenu_CharacterData_C*          K2Node_DynamicCast_AsCreative_Menu_Character_Data; // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB5[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_Message;                        // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_1;                            // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB6[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_Select_Default;                             // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB7[0x7];                                     // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_NameToText_ReturnValue;              // 0x0098(0x0018)()
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB8[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalDatabaseCharacterParameter*         CallFunc_GetDatabaseCharacterParameter_ReturnValue; // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsRaidBoss_ReturnValue;                // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CB9[0x3];                                     // 0x00D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default_2;                           // 0x00D4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry) == 0x000008, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry) == 0x0000E8, "Wrong size on CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, EntryPoint) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::EntryPoint' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_CustomEvent_Loaded) == 0x000008, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_object_Variable) == 0x000010, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, CallFunc_Not_PreBool_ReturnValue) == 0x000019, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_bool_Variable) == 0x00001A, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_byte_Variable) == 0x00001B, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_byte_Variable_1) == 0x00001C, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_bool_Variable_1) == 0x00001D, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_struct_Variable) == 0x000020, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_struct_Variable_1) == 0x000030, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_Event_bIsExpanded) == 0x000040, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_Event_bIsExpanded' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_Event_bIsSelected) == 0x000041, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_Event_bIsSelected' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_Event_ListItemObject) == 0x000048, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_Event_ListItemObject' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_DynamicCast_AsCreative_Menu_Character_Data) == 0x000050, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_DynamicCast_AsCreative_Menu_Character_Data' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_CustomEvent_Message) == 0x000060, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_CustomEvent_Message' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_object_Variable_1) == 0x000070, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, Temp_bool_Variable_2) == 0x000078, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_Select_Default) == 0x000080, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_DynamicCast_AsTexture_2D) == 0x000088, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_DynamicCast_bSuccess_1) == 0x000090, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, CallFunc_Conv_NameToText_ReturnValue) == 0x000098, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::CallFunc_Conv_NameToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_CreateDelegate_OutputDelegate) == 0x0000B0, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_Select_Default_1) == 0x0000C0, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, CallFunc_GetDatabaseCharacterParameter_ReturnValue) == 0x0000C8, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::CallFunc_GetDatabaseCharacterParameter_ReturnValue' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, CallFunc_GetIsRaidBoss_ReturnValue) == 0x0000D0, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::CallFunc_GetIsRaidBoss_ReturnValue' has a wrong offset!");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry, K2Node_Select_Default_2) == 0x0000D4, "Member 'CreativeMenu_ChararcterListEntry_C_ExecuteUbergraph_CreativeMenu_ChararcterListEntry::K2Node_Select_Default_2' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.BP_OnItemSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong size on CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged, bIsSelected) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_BP_OnItemSelectionChanged::bIsSelected' has a wrong offset!");

// Function CreativeMenu_ChararcterListEntry.CreativeMenu_ChararcterListEntry_C.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong alignment on CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged");
static_assert(sizeof(CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong size on CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged");
static_assert(offsetof(CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged, bIsExpanded) == 0x000000, "Member 'CreativeMenu_ChararcterListEntry_C_BP_OnItemExpansionChanged::bIsExpanded' has a wrong offset!");

}

