#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeMenu_ItemData

#include "Basic.hpp"

#include "CreativeMenu_ItemStruct_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CreativeMenu_ItemData.CreativeMenu_ItemData_C
// 0x0050 (0x0078 - 0x0028)
class UCreativeMenu_ItemData_C final : public UObject
{
public:
	struct FCreativeMenu_ItemStruct               Data;                                              // 0x0028(0x0050)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CreativeMenu_ItemData_C">();
	}
	static class UCreativeMenu_ItemData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeMenu_ItemData_C>();
	}
};
static_assert(alignof(UCreativeMenu_ItemData_C) == 0x000008, "Wrong alignment on UCreativeMenu_ItemData_C");
static_assert(sizeof(UCreativeMenu_ItemData_C) == 0x000078, "Wrong size on UCreativeMenu_ItemData_C");
static_assert(offsetof(UCreativeMenu_ItemData_C, Data) == 0x000028, "Member 'UCreativeMenu_ItemData_C::Data' has a wrong offset!");

}

