#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeMenu_ItemStruct

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct CreativeMenu_ItemStruct.CreativeMenu_ItemStruct
// 0x0050 (0x0050 - 0x0000)
struct FCreativeMenu_ItemStruct final
{
public:
	class FName                                   ID_2_A23E510749911B6E3B1496849B229C97;             // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Name_14_ECA775184C9D0E001890FCA959D3742B;          // 0x0008(0x0018)(Edit, BlueprintVisible)
	TSoftObjectPtr<class UTexture2D>              Icon_8_48ABCCD54E2ECE755873E6920735EEEB;           // 0x0020(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
static_assert(alignof(FCreativeMenu_ItemStruct) == 0x000008, "Wrong alignment on FCreativeMenu_ItemStruct");
static_assert(sizeof(FCreativeMenu_ItemStruct) == 0x000050, "Wrong size on FCreativeMenu_ItemStruct");
static_assert(offsetof(FCreativeMenu_ItemStruct, ID_2_A23E510749911B6E3B1496849B229C97) == 0x000000, "Member 'FCreativeMenu_ItemStruct::ID_2_A23E510749911B6E3B1496849B229C97' has a wrong offset!");
static_assert(offsetof(FCreativeMenu_ItemStruct, Name_14_ECA775184C9D0E001890FCA959D3742B) == 0x000008, "Member 'FCreativeMenu_ItemStruct::Name_14_ECA775184C9D0E001890FCA959D3742B' has a wrong offset!");
static_assert(offsetof(FCreativeMenu_ItemStruct, Icon_8_48ABCCD54E2ECE755873E6920735EEEB) == 0x000020, "Member 'FCreativeMenu_ItemStruct::Icon_8_48ABCCD54E2ECE755873E6920735EEEB' has a wrong offset!");

}

