#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeMenu_WazaListEntry

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CreativeMenu_WazaListEntry.CreativeMenu_WazaListEntry_C
// 0x00B8 (0x0330 - 0x0278)
class UCreativeMenu_WazaListEntry_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             ActiveSkillNameText;                               // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Border;                                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Border_1;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_241;                                        // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DamageText;                                        // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ElementBG;                                         // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ElementContainer;                                  // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               FocusFrame;                                        // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_49;                                          // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image2;                                            // 0x02E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               LearnedStateIndicator;                             // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCreativeMenu_WazaData_C*               DataHolder;                                        // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnClick;                                           // 0x0300(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnHover;                                           // 0x0310(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnUnhover;                                         // 0x0320(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void OnUnhover__DelegateSignature(const struct FCreativeMenu_WazaStruct& Data);
	void OnLoaded_FCFF8BC94676FC045B37289098D7A950(class UObject* Loaded);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void OnHover__DelegateSignature(const struct FCreativeMenu_WazaStruct& Data);
	void OnClick__DelegateSignature(class UCreativeMenu_WazaData_C* Data);
	void GetData(EPalWazaID Type, struct FPalWazaDatabaseRaw* OutData);
	ESlateVisibility Get_LearnedStateIndicator_Visibility();
	struct FSlateBrush Get_Image2_Brush();
	class FText Get_DamageText_Text();
	class FText Get_ActiveSkillNameText_Text();
	void ExecuteUbergraph_CreativeMenu_WazaListEntry(int32 EntryPoint);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnEntryReleased();
	void BndEvt__WBP_PassiveSkill_Button_241_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PassiveSkill_Button_241_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__CreativeMenu_WazaListEntry_Button_241_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CreativeMenu_WazaListEntry_C">();
	}
	static class UCreativeMenu_WazaListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeMenu_WazaListEntry_C>();
	}
};
static_assert(alignof(UCreativeMenu_WazaListEntry_C) == 0x000008, "Wrong alignment on UCreativeMenu_WazaListEntry_C");
static_assert(sizeof(UCreativeMenu_WazaListEntry_C) == 0x000330, "Wrong size on UCreativeMenu_WazaListEntry_C");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, UberGraphFrame) == 0x000278, "Member 'UCreativeMenu_WazaListEntry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, ActiveSkillNameText) == 0x000280, "Member 'UCreativeMenu_WazaListEntry_C::ActiveSkillNameText' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Border) == 0x000288, "Member 'UCreativeMenu_WazaListEntry_C::Border' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Border_1) == 0x000290, "Member 'UCreativeMenu_WazaListEntry_C::Border_1' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Button_241) == 0x000298, "Member 'UCreativeMenu_WazaListEntry_C::Button_241' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, DamageText) == 0x0002A0, "Member 'UCreativeMenu_WazaListEntry_C::DamageText' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, ElementBG) == 0x0002A8, "Member 'UCreativeMenu_WazaListEntry_C::ElementBG' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, ElementContainer) == 0x0002B0, "Member 'UCreativeMenu_WazaListEntry_C::ElementContainer' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, FocusFrame) == 0x0002B8, "Member 'UCreativeMenu_WazaListEntry_C::FocusFrame' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Image) == 0x0002C0, "Member 'UCreativeMenu_WazaListEntry_C::Image' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Image_1) == 0x0002C8, "Member 'UCreativeMenu_WazaListEntry_C::Image_1' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Image_2) == 0x0002D0, "Member 'UCreativeMenu_WazaListEntry_C::Image_2' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Image_3) == 0x0002D8, "Member 'UCreativeMenu_WazaListEntry_C::Image_3' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Image_49) == 0x0002E0, "Member 'UCreativeMenu_WazaListEntry_C::Image_49' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, Image2) == 0x0002E8, "Member 'UCreativeMenu_WazaListEntry_C::Image2' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, LearnedStateIndicator) == 0x0002F0, "Member 'UCreativeMenu_WazaListEntry_C::LearnedStateIndicator' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, DataHolder) == 0x0002F8, "Member 'UCreativeMenu_WazaListEntry_C::DataHolder' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, OnClick) == 0x000300, "Member 'UCreativeMenu_WazaListEntry_C::OnClick' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, OnHover) == 0x000310, "Member 'UCreativeMenu_WazaListEntry_C::OnHover' has a wrong offset!");
static_assert(offsetof(UCreativeMenu_WazaListEntry_C, OnUnhover) == 0x000320, "Member 'UCreativeMenu_WazaListEntry_C::OnUnhover' has a wrong offset!");

}

