#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FNetSpawnInfo

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "FSpawnExtraParams_structs.hpp"


namespace SDK
{

// UserDefinedStruct FNetSpawnInfo.FNetSpawnInfo
// 0x0030 (0x0030 - 0x0000)
struct FFNetSpawnInfo final
{
public:
	struct FVector                                SpawnLocation_5_AB4D0EB240DC620DF6243D8E99294824;  // 0x0000(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFSpawnExtraParams                     ExtraParams_16_2C33F09C4E9D83ABB6FC099BBC63690C;   // 0x0018(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FFNetSpawnInfo) == 0x000008, "Wrong alignment on FFNetSpawnInfo");
static_assert(sizeof(FFNetSpawnInfo) == 0x000030, "Wrong size on FFNetSpawnInfo");
static_assert(offsetof(FFNetSpawnInfo, SpawnLocation_5_AB4D0EB240DC620DF6243D8E99294824) == 0x000000, "Member 'FFNetSpawnInfo::SpawnLocation_5_AB4D0EB240DC620DF6243D8E99294824' has a wrong offset!");
static_assert(offsetof(FFNetSpawnInfo, ExtraParams_16_2C33F09C4E9D83ABB6FC099BBC63690C) == 0x000018, "Member 'FFNetSpawnInfo::ExtraParams_16_2C33F09C4E9D83ABB6FC099BBC63690C' has a wrong offset!");

}

