#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FStoredTemplateStruct

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK
{

// UserDefinedStruct FStoredTemplateStruct.FStoredTemplateStruct
// 0x00C0 (0x00C0 - 0x0000)
struct FFStoredTemplateStruct final
{
public:
	class FString                                 Name_2_4C88D3E24986B829D468F79C3EDA99FE;           // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, HasGetValueTypeHash)
	class FString                                 Version_18_7B2176594EE7D89854DFC38FFDB5FD49;       // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, HasGetValueTypeHash)
	class FName                                   CharacterID_20_58AEA1164F8FD20AC65724AFB119A88D;   // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalGenderType                                Gender_23_43B13A884CA8C3F664336191D22EED04;        // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A71[0x3];                                     // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Level_26_25A0A1554F11C43C40128AAADC07C39A;         // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Rank_28_7F702DB34648000F0ADC39A6C88DC779;          // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RankHP_30_FDE0B0994BEA081D57B9539C1BBEFD2D;        // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RankAttack_32_F3B27EF843A91300B5ACD9AB910380D7;    // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RankDefence_35_012AA81044F80537A3C025B9B8C8C33B;   // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RankCraftSpeed_37_7CE0C2154089AA3409745CA6FA9D1B5F; // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRarePal_82_1FE20F4F49A8E1E45B23AA81A8EAB4A9;     // 0x0044(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A72[0x3];                                     // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<uint8>                                 EqupWaza_86_6CB50C25413CEF3DBBD8428992E74E81;      // 0x0048(0x0010)(Edit, BlueprintVisible, SaveGame)
	TArray<uint8>                                 MasteredWaza_88_DB1E03BE48A9DBCA207D6AB990AF82DE;  // 0x0058(0x0010)(Edit, BlueprintVisible, SaveGame)
	struct FFixedPoint64                          HP_49_7F225DA14A140ADAC345109D74E5509F;            // 0x0068(0x0008)(Edit, BlueprintVisible, SaveGame, NoDestructor)
	int32                                         TalentHP_52_47F4238E46DB3FE999CFE9935F5F70FE;      // 0x0070(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TalentMelee_54_7B88B7344F6BA08754DADEB0A446BF3D;   // 0x0074(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TalentShot_56_7AD36FA942942ADBD2830D8D227A1C90;    // 0x0078(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TalentDefense_58_50B3E1C64FCC09E662EF3F9F5689D950; // 0x007C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        FullStomach_61_1050EDB64403F3F81F4474BDCC45D1E5;   // 0x0080(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           PassiveSkillList_65_CE204CD54AD4691A47147EBD8BF2839B; // 0x0088(0x0010)(Edit, BlueprintVisible, SaveGame)
	struct FFixedPoint64                          MaxHP_69_FF249F8443F56E991808A7AD41A61683;         // 0x0098(0x0008)(Edit, BlueprintVisible, SaveGame, NoDestructor)
	int32                                         CraftSpeed_73_AACF24F64C3785C86AA18F9BF9252559;    // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A73[0x4];                                     // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFixedPoint64                          MaxSP_76_884549744C82188767E9709A4B897606;         // 0x00A8(0x0008)(Edit, BlueprintVisible, SaveGame, NoDestructor)
	double                                        SanityValue_79_E629C0FA4BC5E772D39ED280E2ABE23A;   // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxFullStomach_81_1ED6CD114930C6838D65C29E655CC66C; // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FFStoredTemplateStruct) == 0x000008, "Wrong alignment on FFStoredTemplateStruct");
static_assert(sizeof(FFStoredTemplateStruct) == 0x0000C0, "Wrong size on FFStoredTemplateStruct");
static_assert(offsetof(FFStoredTemplateStruct, Name_2_4C88D3E24986B829D468F79C3EDA99FE) == 0x000000, "Member 'FFStoredTemplateStruct::Name_2_4C88D3E24986B829D468F79C3EDA99FE' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, Version_18_7B2176594EE7D89854DFC38FFDB5FD49) == 0x000010, "Member 'FFStoredTemplateStruct::Version_18_7B2176594EE7D89854DFC38FFDB5FD49' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, CharacterID_20_58AEA1164F8FD20AC65724AFB119A88D) == 0x000020, "Member 'FFStoredTemplateStruct::CharacterID_20_58AEA1164F8FD20AC65724AFB119A88D' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, Gender_23_43B13A884CA8C3F664336191D22EED04) == 0x000028, "Member 'FFStoredTemplateStruct::Gender_23_43B13A884CA8C3F664336191D22EED04' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, Level_26_25A0A1554F11C43C40128AAADC07C39A) == 0x00002C, "Member 'FFStoredTemplateStruct::Level_26_25A0A1554F11C43C40128AAADC07C39A' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, Rank_28_7F702DB34648000F0ADC39A6C88DC779) == 0x000030, "Member 'FFStoredTemplateStruct::Rank_28_7F702DB34648000F0ADC39A6C88DC779' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, RankHP_30_FDE0B0994BEA081D57B9539C1BBEFD2D) == 0x000034, "Member 'FFStoredTemplateStruct::RankHP_30_FDE0B0994BEA081D57B9539C1BBEFD2D' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, RankAttack_32_F3B27EF843A91300B5ACD9AB910380D7) == 0x000038, "Member 'FFStoredTemplateStruct::RankAttack_32_F3B27EF843A91300B5ACD9AB910380D7' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, RankDefence_35_012AA81044F80537A3C025B9B8C8C33B) == 0x00003C, "Member 'FFStoredTemplateStruct::RankDefence_35_012AA81044F80537A3C025B9B8C8C33B' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, RankCraftSpeed_37_7CE0C2154089AA3409745CA6FA9D1B5F) == 0x000040, "Member 'FFStoredTemplateStruct::RankCraftSpeed_37_7CE0C2154089AA3409745CA6FA9D1B5F' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, IsRarePal_82_1FE20F4F49A8E1E45B23AA81A8EAB4A9) == 0x000044, "Member 'FFStoredTemplateStruct::IsRarePal_82_1FE20F4F49A8E1E45B23AA81A8EAB4A9' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, EqupWaza_86_6CB50C25413CEF3DBBD8428992E74E81) == 0x000048, "Member 'FFStoredTemplateStruct::EqupWaza_86_6CB50C25413CEF3DBBD8428992E74E81' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, MasteredWaza_88_DB1E03BE48A9DBCA207D6AB990AF82DE) == 0x000058, "Member 'FFStoredTemplateStruct::MasteredWaza_88_DB1E03BE48A9DBCA207D6AB990AF82DE' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, HP_49_7F225DA14A140ADAC345109D74E5509F) == 0x000068, "Member 'FFStoredTemplateStruct::HP_49_7F225DA14A140ADAC345109D74E5509F' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, TalentHP_52_47F4238E46DB3FE999CFE9935F5F70FE) == 0x000070, "Member 'FFStoredTemplateStruct::TalentHP_52_47F4238E46DB3FE999CFE9935F5F70FE' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, TalentMelee_54_7B88B7344F6BA08754DADEB0A446BF3D) == 0x000074, "Member 'FFStoredTemplateStruct::TalentMelee_54_7B88B7344F6BA08754DADEB0A446BF3D' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, TalentShot_56_7AD36FA942942ADBD2830D8D227A1C90) == 0x000078, "Member 'FFStoredTemplateStruct::TalentShot_56_7AD36FA942942ADBD2830D8D227A1C90' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, TalentDefense_58_50B3E1C64FCC09E662EF3F9F5689D950) == 0x00007C, "Member 'FFStoredTemplateStruct::TalentDefense_58_50B3E1C64FCC09E662EF3F9F5689D950' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, FullStomach_61_1050EDB64403F3F81F4474BDCC45D1E5) == 0x000080, "Member 'FFStoredTemplateStruct::FullStomach_61_1050EDB64403F3F81F4474BDCC45D1E5' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, PassiveSkillList_65_CE204CD54AD4691A47147EBD8BF2839B) == 0x000088, "Member 'FFStoredTemplateStruct::PassiveSkillList_65_CE204CD54AD4691A47147EBD8BF2839B' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, MaxHP_69_FF249F8443F56E991808A7AD41A61683) == 0x000098, "Member 'FFStoredTemplateStruct::MaxHP_69_FF249F8443F56E991808A7AD41A61683' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, CraftSpeed_73_AACF24F64C3785C86AA18F9BF9252559) == 0x0000A0, "Member 'FFStoredTemplateStruct::CraftSpeed_73_AACF24F64C3785C86AA18F9BF9252559' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, MaxSP_76_884549744C82188767E9709A4B897606) == 0x0000A8, "Member 'FFStoredTemplateStruct::MaxSP_76_884549744C82188767E9709A4B897606' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, SanityValue_79_E629C0FA4BC5E772D39ED280E2ABE23A) == 0x0000B0, "Member 'FFStoredTemplateStruct::SanityValue_79_E629C0FA4BC5E772D39ED280E2ABE23A' has a wrong offset!");
static_assert(offsetof(FFStoredTemplateStruct, MaxFullStomach_81_1ED6CD114930C6838D65C29E655CC66C) == 0x0000B8, "Member 'FFStoredTemplateStruct::MaxFullStomach_81_1ED6CD114930C6838D65C29E655CC66C' has a wrong offset!");

}

