#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BossDemoDesert

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_BossDemoBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_BossDemoDesert.WBP_BossDemoDesert_C
// 0x0020 (0x0428 - 0x0408)
class UWBP_BossDemoDesert_C final : public UWBP_BossDemoBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_395;                                         // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BossBattle_BossCut02_C*            WBP_BossBattle_BossCut02;                          // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BossBattle_BossCutBase02_C*        WBP_BossBattle_BossCutBase02;                      // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AnmEvent_Open();
	void ExecuteUbergraph_WBP_BossDemoDesert(int32 EntryPoint);
	void Finished_521992B04801673A8A4B5C9041710F99();
	void OnStartEvent();
	void SetupText();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_BossDemoDesert_C">();
	}
	static class UWBP_BossDemoDesert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BossDemoDesert_C>();
	}
};
static_assert(alignof(UWBP_BossDemoDesert_C) == 0x000008, "Wrong alignment on UWBP_BossDemoDesert_C");
static_assert(sizeof(UWBP_BossDemoDesert_C) == 0x000428, "Wrong size on UWBP_BossDemoDesert_C");
static_assert(offsetof(UWBP_BossDemoDesert_C, UberGraphFrame) == 0x000408, "Member 'UWBP_BossDemoDesert_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_BossDemoDesert_C, Image_395) == 0x000410, "Member 'UWBP_BossDemoDesert_C::Image_395' has a wrong offset!");
static_assert(offsetof(UWBP_BossDemoDesert_C, WBP_BossBattle_BossCut02) == 0x000418, "Member 'UWBP_BossDemoDesert_C::WBP_BossBattle_BossCut02' has a wrong offset!");
static_assert(offsetof(UWBP_BossDemoDesert_C, WBP_BossBattle_BossCutBase02) == 0x000420, "Member 'UWBP_BossDemoDesert_C::WBP_BossBattle_BossCutBase02' has a wrong offset!");

}

