#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Notification

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Notification.WBP_Notification_C
// 0x0010 (0x0288 - 0x0278)
class UWBP_Notification_C final : public UUserWidget
{
public:
	class UImage*                                 Image_46;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             NotificationText;                                  // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ShowNotification_Internal();
	void ShowNotification(const class FText& Message, double Duration);
	void HideNotification();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Notification_C">();
	}
	static class UWBP_Notification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Notification_C>();
	}
};
static_assert(alignof(UWBP_Notification_C) == 0x000008, "Wrong alignment on UWBP_Notification_C");
static_assert(sizeof(UWBP_Notification_C) == 0x000288, "Wrong size on UWBP_Notification_C");
static_assert(offsetof(UWBP_Notification_C, Image_46) == 0x000278, "Member 'UWBP_Notification_C::Image_46' has a wrong offset!");
static_assert(offsetof(UWBP_Notification_C, NotificationText) == 0x000280, "Member 'UWBP_Notification_C::NotificationText' has a wrong offset!");

}

