#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WazaButton

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_WazaButton.WBP_WazaButton_C.SetLearnedState
// 0x002C (0x002C - 0x0000)
struct WBP_WazaButton_C_SetLearnedState final
{
public:
	bool                                          Param_bIsLearned;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B82[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0004(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0018(0x0014)()
};
static_assert(alignof(WBP_WazaButton_C_SetLearnedState) == 0x000004, "Wrong alignment on WBP_WazaButton_C_SetLearnedState");
static_assert(sizeof(WBP_WazaButton_C_SetLearnedState) == 0x00002C, "Wrong size on WBP_WazaButton_C_SetLearnedState");
static_assert(offsetof(WBP_WazaButton_C_SetLearnedState, Param_bIsLearned) == 0x000000, "Member 'WBP_WazaButton_C_SetLearnedState::Param_bIsLearned' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_SetLearnedState, K2Node_MakeStruct_SlateColor) == 0x000004, "Member 'WBP_WazaButton_C_SetLearnedState::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_SetLearnedState, K2Node_MakeStruct_SlateColor_1) == 0x000018, "Member 'WBP_WazaButton_C_SetLearnedState::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");

// Function WBP_WazaButton.WBP_WazaButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_WazaButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_WazaButton_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_WazaButton_C_PreConstruct");
static_assert(sizeof(WBP_WazaButton_C_PreConstruct) == 0x000001, "Wrong size on WBP_WazaButton_C_PreConstruct");
static_assert(offsetof(WBP_WazaButton_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_WazaButton_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_WazaButton.WBP_WazaButton_C.OnLearnedStateChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature final
{
public:
	bool                                          Param_bIsLearned;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B83[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_WazaButton_C*                      WazaElement;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature) == 0x000008, "Wrong alignment on WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature");
static_assert(sizeof(WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature) == 0x000010, "Wrong size on WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature");
static_assert(offsetof(WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature, Param_bIsLearned) == 0x000000, "Member 'WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature::Param_bIsLearned' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature, WazaElement) == 0x000008, "Member 'WBP_WazaButton_C_OnLearnedStateChanged__DelegateSignature::WazaElement' has a wrong offset!");

// Function WBP_WazaButton.WBP_WazaButton_C.ExecuteUbergraph_WBP_WazaButton
// 0x0068 (0x0068 - 0x0000)
struct WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0004(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0018(0x0014)()
	bool                                          K2Node_Event_IsDesignTime;                         // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B84[0x3];                                     // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_Map_Find_Value;                           // 0x0030(0x0030)(HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton) == 0x000008, "Wrong alignment on WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton");
static_assert(sizeof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton) == 0x000068, "Wrong size on WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton");
static_assert(offsetof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton, EntryPoint) == 0x000000, "Member 'WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton, K2Node_MakeStruct_SlateColor) == 0x000004, "Member 'WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton, K2Node_MakeStruct_SlateColor_1) == 0x000018, "Member 'WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton, K2Node_Event_IsDesignTime) == 0x00002C, "Member 'WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton, CallFunc_Map_Find_Value) == 0x000030, "Member 'WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton, CallFunc_Map_Find_ReturnValue) == 0x000060, "Member 'WBP_WazaButton_C_ExecuteUbergraph_WBP_WazaButton::CallFunc_Map_Find_ReturnValue' has a wrong offset!");

}

