#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalWazaList

#include "Basic.hpp"

#include "WBP_PalWazaList_classes.hpp"
#include "WBP_PalWazaList_parameters.hpp"


namespace SDK
{

// Function WBP_PalWazaList.WBP_PalWazaList_C.Refresh
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PalWazaList_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.OnWazaStateChanged
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsLearned                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_WazaButton_C*                WazaElement                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWazaList_C::OnWazaStateChanged(bool bIsLearned, class UWBP_WazaButton_C* WazaElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "OnWazaStateChanged");

	Params::WBP_PalWazaList_C_OnWazaStateChanged Parms{};

	Parms.bIsLearned = bIsLearned;
	Parms.WazaElement = WazaElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.OnWazaRemoved_Delegate__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPalWazaID                              WazaID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWazaList_C::OnWazaRemoved_Delegate__DelegateSignature(EPalWazaID WazaID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "OnWazaRemoved_Delegate__DelegateSignature");

	Params::WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature Parms{};

	Parms.WazaID = WazaID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.OnWazaAdded_Delegate__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPalWazaID                              WazaID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWazaList_C::OnWazaAdded_Delegate__DelegateSignature(EPalWazaID WazaID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "OnWazaAdded_Delegate__DelegateSignature");

	Params::WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature Parms{};

	Parms.WazaID = WazaID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.OnConfirm__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_PalWazaList_C::OnConfirm__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "OnConfirm__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.ExecuteUbergraph_WBP_PalWazaList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWazaList_C::ExecuteUbergraph_WBP_PalWazaList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "ExecuteUbergraph_WBP_PalWazaList");

	Params::WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalWazaList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.BndEvt__WBP_PalWazaList_WBP_Button_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_PalWazaList_C::BndEvt__WBP_PalWazaList_WBP_Button_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "BndEvt__WBP_PalWazaList_WBP_Button_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.BndEvt__WBP_PalWazaList_WBP_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_PalWazaList_C::BndEvt__WBP_PalWazaList_WBP_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "BndEvt__WBP_PalWazaList_WBP_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalWazaList.WBP_PalWazaList_C.BndEvt__WBP_PalWazaList_WBP_Button_1_K2Node_ComponentBoundEvent_1_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_PalWazaList_C::BndEvt__WBP_PalWazaList_WBP_Button_1_K2Node_ComponentBoundEvent_1_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWazaList_C", "BndEvt__WBP_PalWazaList_WBP_Button_1_K2Node_ComponentBoundEvent_1_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

