#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalEditor

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalEditor.WBP_PalEditor_C
// 0x0978 (0x0D80 - 0x0408)
class UWBP_PalEditor_C final : public UPalUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           ActiveSkillList;                                   // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Border;                                            // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Border_1;                                          // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Border_2;                                          // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button;                                            // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_1;                                          // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_113;                                        // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_157;                                        // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_184;                                        // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              CheckBox_1;                                        // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       EditableTextBox_488;                               // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               FocusFrame;                                        // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               FocusFrame_1;                                      // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               FocusFrame_2;                                      // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 GenderIcon;                                        // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             HistoryList;                                       // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               HistoryWindow;                                     // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           HistoryWindowInner;                                // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_5;                                           // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_6;                                           // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_7;                                           // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_8;                                           // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_9;                                           // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_10;                                          // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_11;                                          // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_12;                                          // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_13;                                          // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_14;                                          // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_15;                                          // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_16;                                          // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_64;                                          // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             MaxHPText;                                         // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           PassiveContainer;                                  // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ShuffleIcon;                                       // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ShuffleIcon_1;                                     // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox;                                           // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_1;                                         // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_2;                                         // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_3;                                         // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_4;                                         // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_5;                                         // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_6;                                         // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_7;                                         // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_8;                                         // 0x0590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_9;                                         // 0x0598(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_10;                                        // 0x05A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_13;                                        // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_14;                                        // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_15;                                        // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_16;                                        // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_147;                                       // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             TemplateList;                                      // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               TemplateWindow;                                    // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           TemplateWindowInner;                               // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           UpgradesContainer;                                 // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UListView*                              WazaAvailableList;                                 // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           WazaAvailablePage;                                 // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UListView*                              WazaMasteredList;                                  // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           WazaMasteredPage;                                  // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ActiveSkill_C*                     WBP_ActiveSkill;                                   // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ActiveSkill_C*                     WBP_ActiveSkill_1;                                 // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ActiveSkill_C*                     WBP_ActiveSkill_2;                                 // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button;                                        // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_1;                                      // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_2;                                      // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_3;                                      // 0x0640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_4;                                      // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_5;                                      // 0x0650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_6;                                      // 0x0658(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_7;                                      // 0x0660(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_8;                                      // 0x0668(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_11;                                     // 0x0670(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Button_C*                          WBP_Button_299;                                    // 0x0678(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalCharacterInfo_C*                WBP_PalCharacterInfo;                              // 0x0680(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PassiveList_C*                     WBP_PassiveList_101;                               // 0x0688(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PassiveSkill_C*                    WBP_PassiveSkill;                                  // 0x0690(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PassiveSkill_C*                    WBP_PassiveSkill_1;                                // 0x0698(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PassiveSkill_C*                    WBP_PassiveSkill_2;                                // 0x06A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PassiveSkill_C*                    WBP_PassiveSkill_3;                                // 0x06A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Tooltip_C*                         WBP_Tooltip;                                       // 0x06B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_1001;                               // 0x06B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FPalIndividualCharacterSaveParameter   CharacterParams;                                   // 0x06C0(0x02C0)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FName                                   SelectedID;                                        // 0x0980(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                   SelectedName;                                      // 0x0988(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	FMulticastInlineDelegateProperty_             OnFinish;                                          // 0x09A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UWBP_PassiveSkill_C*                    CurrentlySelectedPassiveSlot;                      // 0x09B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalGenderType                                Gender;                                            // 0x09B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CA1[0x7];                                     // 0x09B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalWazaList_C*                     WazaList;                                          // 0x09C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PassiveList_C*                     PassiveList;                                       // 0x09C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bAllowUniqueAbilitiesOnAnyone;                     // 0x09D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_3CA2[0x7];                                     // 0x09D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_PalEditHistoryComponent_C*          HistoryComponent;                                  // 0x09D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FPalIndividualCharacterSaveParameter   CurrentParams;                                     // 0x09E0(0x02C0)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UWBP_PassiveSkill_C*>            PassiveSlots;                                      // 0x0CA0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UWBP_ActiveSkill_C*>             ActiveSkillSlots;                                  // 0x0CB0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                          bDisableEvents;                                    // 0x0CC0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsTooltipVisible;                                 // 0x0CC1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CA3[0x2];                                     // 0x0CC2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalUIActionBindData                   EscapeHandle;                                      // 0x0CC4(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	class FString                                 ModVersion;                                        // 0x0CC8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UCreativeMenuSaveObject_C*              SaveObject;                                        // 0x0CD8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<class UCreativeMenu_WazaData_C*>       AllWazaDataArray;                                  // 0x0CE0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<EPalWazaID, class UCreativeMenu_WazaData_C*> AllWazaDataMap;                                    // 0x0CF0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UCreativeMenu_WazaData_C*>       AvailableWazaDataArray;                            // 0x0D40(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UCreativeMenu_WazaData_C*>       MasteredWazaDataArray;                             // 0x0D50(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UCreativeMenu_WazaData_C*>       EquippedWazaDataArray;                             // 0x0D60(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UWBP_ActiveSkill_C*                     SelectedActiveSkillSlot;                           // 0x0D70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentActiveSkillIndex;                           // 0x0D78(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsHealthOverflowing;                              // 0x0D7C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bShouldObtainAsEgg;                                // 0x0D7D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	TArray<EPalWazaID> WazaStringToArray(const class FString& WazaString);
	void UpdateMaxHP();
	void SnapTooltipToCursor();
	void ShowSkillTooltip(EPalWazaID WazaID, bool ShowKeyGuide);
	void ShowPassiveTooltip(class FName ID, bool ShowKeyGuide);
	void ShowGeneralTooltip(const class FText& Title, const class FText& Content);
	void SetupWaza();
	void SetupPassives();
	void SetupMasteredSkills();
	void SetupEvents();
	void SetupButtons();
	void SetupBaseStats();
	void SetupAvailableSkills();
	void SetupActiveSkills();
	void SetSpinBoxMaxValue(class USpinBox* Param_SpinBox, double MaxValue);
	void SetSelectedPassiveSlot(class UWBP_PassiveSkill_C* Param_Button);
	void SetGender(EPalGenderType Param_Gender);
	void SetCharacterID(class FName ID);
	void RefreshActiveSkillSlots();
	void RandomizePassives();
	void RandomizeIVs();
	void PrintToModLoader(const class FString& Message);
	void PreConstruct(bool IsDesignTime);
	TArray<class FName> PassiveStringToArray(const class FString& PassiveString);
	bool ParseStringToParam(const class FString& String);
	void ParseParamToString(const struct FPalIndividualCharacterSaveParameter& Param_Param);
	void OpenPassiveSkillList(class UWBP_PassiveSkill_C* SelectedButton);
	void OnWazaUnlearn(EPalWazaID WazaID);
	void OnWazaUnequip(EPalWazaID WazaID);
	void OnWazaLearn(EPalWazaID WazaEnum);
	void OnWazaEquip(int32 Param_Slot, EPalWazaID WazaID);
	void OnTemplateEntryUnhovered(class UWBP_HistoryButton_C* Param_Button);
	void OnTemplateEntryHovered(class UWBP_HistoryButton_C* Param_Button);
	void OnSkillUnhovered(const struct FCreativeMenu_WazaStruct& Data);
	void OnSkillSlotUnhovered();
	void OnSkillSlotHovered(EPalWazaID ID);
	void OnSkillHovered(const struct FCreativeMenu_WazaStruct& Data);
	void OnPresetSelected(const struct FPalIndividualCharacterSaveParameter& Data);
	void OnPassiveSlotUnhovered();
	void OnPassiveSlotRightClick(class UWBP_PassiveSkill_C* Param_Button);
	void OnPassiveSlotHovered(class UWBP_PassiveSkill_C* Param_Button, class FName ID);
	void OnPassiveSelected(class FName ID);
	struct FEventReply OnMouseMove(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnMasteredSkillSelected(class UCreativeMenu_WazaData_C* Data);
	struct FEventReply OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	void OnHistoryEntryUnhovered(class UWBP_HistoryButton_C* Param_Button);
	void OnHistoryEntryHovered(class UWBP_HistoryButton_C* Param_Button);
	void OnFinish__DelegateSignature(const struct FPalIndividualCharacterSaveParameter& CharacterParam, const struct FFSpawnExtraParams& ExtraParams);
	void OnDeleteTemplateEntry(class UWBP_HistoryButton_C* Param_Button);
	void OnDeleteHistoryEntry(class UWBP_HistoryButton_C* Param_Button);
	void OnCharacterIDChanged(class FName OldID, class FName NewID);
	void OnAvailableWazaClicked(class UCreativeMenu_WazaData_C* Data);
	void OnActiveSkillRightClicked(class UWBP_ActiveSkill_C* Param_Button);
	void OnActiveSkillClicked(class UWBP_ActiveSkill_C* Param_Button, EPalWazaID ID);
	void Log(const class FText& LogText);
	void LoadTemplates();
	void LoadHistory();
	void HideTooltip();
	void HideSideBars();
	TArray<EPalWazaID> GetWazaArrayFromByteArray(TArray<uint8>& ByteArray);
	void GetStringFromWazas(TArray<EPalWazaID>& Array, class FString* Output_Get);
	class FString GetStringFromPassiveButtons();
	void GetPalData(class FName ID, struct FPalCharacterParameterDatabaseRow* Out_Row);
	int32 GetMaxUpgradeRank();
	void GetElementIcon(EPalElementType Element, TSoftObjectPtr<class UTexture2D>* Icon);
	void Finish(bool bCaptureInstantly, bool Param_bShouldObtainAsEgg, int32 SpawnAmount);
	void BndEvt__WBP_PalEditor_WBP_Button_3_K2Node_ComponentBoundEvent_47_OnButtonUnhovered__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_3_K2Node_ComponentBoundEvent_46_OnButtonHovered__DelegateSignature(class UWBP_Button_C* Param_Button);
	void BndEvt__WBP_PalEditor_WBP_Button_3_K2Node_ComponentBoundEvent_45_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_2_K2Node_ComponentBoundEvent_62_OnButtonHovered__DelegateSignature(class UWBP_Button_C* Param_Button);
	void BndEvt__WBP_PalEditor_WBP_Button_2_K2Node_ComponentBoundEvent_15_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_299_K2Node_ComponentBoundEvent_7_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_1_K2Node_ComponentBoundEvent_17_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_11_K2Node_ComponentBoundEvent_57_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_ActiveSkill_K2Node_ComponentBoundEvent_50_OnClicked__DelegateSignature(class UWBP_ActiveSkill_C* Param_Button, EPalWazaID ID);
	void BndEvt__WBP_PalEditor_WBP_ActiveSkill_2_K2Node_ComponentBoundEvent_52_OnClicked__DelegateSignature(class UWBP_ActiveSkill_C* Param_Button, EPalWazaID ID);
	void BndEvt__WBP_PalEditor_WBP_ActiveSkill_1_K2Node_ComponentBoundEvent_51_OnClicked__DelegateSignature(class UWBP_ActiveSkill_C* Param_Button, EPalWazaID ID);
	void BndEvt__WBP_PalEditor_WazaMasteredList_K2Node_ComponentBoundEvent_35_OnListEntryInitializedDynamic__DelegateSignature(class UObject* Item, class UUserWidget* Widget);
	void BndEvt__WBP_PalEditor_WazaAvailableList_K2Node_ComponentBoundEvent_53_OnListEntryInitializedDynamic__DelegateSignature(class UObject* Item, class UUserWidget* Widget);
	void BndEvt__WBP_PalEditor_SpinBox_K2Node_ComponentBoundEvent_1_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_9_K2Node_ComponentBoundEvent_27_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_8_K2Node_ComponentBoundEvent_26_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_7_K2Node_ComponentBoundEvent_21_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_6_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_5_K2Node_ComponentBoundEvent_12_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_4_K2Node_ComponentBoundEvent_13_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_3_K2Node_ComponentBoundEvent_16_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_1_K2Node_ComponentBoundEvent_3_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_16_K2Node_ComponentBoundEvent_59_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_15_K2Node_ComponentBoundEvent_58_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_14_K2Node_ComponentBoundEvent_34_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_147_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_13_K2Node_ComponentBoundEvent_32_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_SpinBox_10_K2Node_ComponentBoundEvent_25_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__WBP_PalEditor_EditableTextBox_488_K2Node_ComponentBoundEvent_6_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__WBP_PalEditor_CheckBox_1_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__WBP_PalEditor_Button_K2Node_ComponentBoundEvent_43_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_K2Node_ComponentBoundEvent_42_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_1_K2Node_ComponentBoundEvent_49_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_1_K2Node_ComponentBoundEvent_48_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_1_K2Node_ComponentBoundEvent_44_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_184_K2Node_ComponentBoundEvent_61_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_184_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_157_K2Node_ComponentBoundEvent_60_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_157_K2Node_ComponentBoundEvent_33_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_113_K2Node_ComponentBoundEvent_20_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_113_K2Node_ComponentBoundEvent_19_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_PalEditor_Button_113_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature();
	void BackToMain();
	void AssignPassives();
	void ExecuteUbergraph_WBP_PalEditor(int32 EntryPoint);
	void Construct();
	void Close();
	class FString BuildSettingsString(TArray<class FString>& StringArray);
	void BndEvt__WBP_PalEditor_WBP_PassiveSkill_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature(class UWBP_PassiveSkill_C* Param_Button, class FName ID);
	void BndEvt__WBP_PalEditor_WBP_PassiveSkill_3_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature(class UWBP_PassiveSkill_C* Param_Button, class FName ID);
	void BndEvt__WBP_PalEditor_WBP_PassiveSkill_2_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature(class UWBP_PassiveSkill_C* Param_Button, class FName ID);
	void BndEvt__WBP_PalEditor_WBP_PassiveSkill_1_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature(class UWBP_PassiveSkill_C* Param_Button, class FName ID);
	void BndEvt__WBP_PalEditor_WBP_PassiveList_101_K2Node_ComponentBoundEvent_31_Delegate_OnPassiveUnhovered__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_PassiveList_101_K2Node_ComponentBoundEvent_30_Delegate_OnPassiveHovered__DelegateSignature(class FName ID);
	void BndEvt__WBP_PalEditor_WBP_PassiveList_101_K2Node_ComponentBoundEvent_29_OnSelect__DelegateSignature(class FName ID);
	void BndEvt__WBP_PalEditor_WBP_PassiveList_101_K2Node_ComponentBoundEvent_28_OnBackAction__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_K2Node_ComponentBoundEvent_8_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_K2Node_ComponentBoundEvent_24_OnButtonUnhovered__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_K2Node_ComponentBoundEvent_23_OnButtonHovered__DelegateSignature(class UWBP_Button_C* Param_Button);
	void BndEvt__WBP_PalEditor_WBP_Button_8_K2Node_ComponentBoundEvent_54_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_7_K2Node_ComponentBoundEvent_56_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_6_K2Node_ComponentBoundEvent_41_OnButtonUnhovered__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_6_K2Node_ComponentBoundEvent_40_OnButtonHovered__DelegateSignature(class UWBP_Button_C* Param_Button);
	void BndEvt__WBP_PalEditor_WBP_Button_6_K2Node_ComponentBoundEvent_39_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_5_K2Node_ComponentBoundEvent_38_OnButtonUnhovered__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_5_K2Node_ComponentBoundEvent_37_OnButtonHovered__DelegateSignature(class UWBP_Button_C* Param_Button);
	void BndEvt__WBP_PalEditor_WBP_Button_5_K2Node_ComponentBoundEvent_36_OnButtonClicked__DelegateSignature();
	void BndEvt__WBP_PalEditor_WBP_Button_4_K2Node_ComponentBoundEvent_55_OnButtonClicked__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PalEditor_C">();
	}
	static class UWBP_PalEditor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalEditor_C>();
	}
};
static_assert(alignof(UWBP_PalEditor_C) == 0x000008, "Wrong alignment on UWBP_PalEditor_C");
static_assert(sizeof(UWBP_PalEditor_C) == 0x000D80, "Wrong size on UWBP_PalEditor_C");
static_assert(offsetof(UWBP_PalEditor_C, UberGraphFrame) == 0x000408, "Member 'UWBP_PalEditor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, ActiveSkillList) == 0x000410, "Member 'UWBP_PalEditor_C::ActiveSkillList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Border) == 0x000418, "Member 'UWBP_PalEditor_C::Border' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Border_1) == 0x000420, "Member 'UWBP_PalEditor_C::Border_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Border_2) == 0x000428, "Member 'UWBP_PalEditor_C::Border_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Button) == 0x000430, "Member 'UWBP_PalEditor_C::Button' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Button_1) == 0x000438, "Member 'UWBP_PalEditor_C::Button_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Button_113) == 0x000440, "Member 'UWBP_PalEditor_C::Button_113' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Button_157) == 0x000448, "Member 'UWBP_PalEditor_C::Button_157' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Button_184) == 0x000450, "Member 'UWBP_PalEditor_C::Button_184' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, CheckBox_1) == 0x000458, "Member 'UWBP_PalEditor_C::CheckBox_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, EditableTextBox_488) == 0x000460, "Member 'UWBP_PalEditor_C::EditableTextBox_488' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, FocusFrame) == 0x000468, "Member 'UWBP_PalEditor_C::FocusFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, FocusFrame_1) == 0x000470, "Member 'UWBP_PalEditor_C::FocusFrame_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, FocusFrame_2) == 0x000478, "Member 'UWBP_PalEditor_C::FocusFrame_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, GenderIcon) == 0x000480, "Member 'UWBP_PalEditor_C::GenderIcon' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, HistoryList) == 0x000488, "Member 'UWBP_PalEditor_C::HistoryList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, HistoryWindow) == 0x000490, "Member 'UWBP_PalEditor_C::HistoryWindow' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, HistoryWindowInner) == 0x000498, "Member 'UWBP_PalEditor_C::HistoryWindowInner' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image) == 0x0004A0, "Member 'UWBP_PalEditor_C::Image' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_1) == 0x0004A8, "Member 'UWBP_PalEditor_C::Image_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_2) == 0x0004B0, "Member 'UWBP_PalEditor_C::Image_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_3) == 0x0004B8, "Member 'UWBP_PalEditor_C::Image_3' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_4) == 0x0004C0, "Member 'UWBP_PalEditor_C::Image_4' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_5) == 0x0004C8, "Member 'UWBP_PalEditor_C::Image_5' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_6) == 0x0004D0, "Member 'UWBP_PalEditor_C::Image_6' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_7) == 0x0004D8, "Member 'UWBP_PalEditor_C::Image_7' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_8) == 0x0004E0, "Member 'UWBP_PalEditor_C::Image_8' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_9) == 0x0004E8, "Member 'UWBP_PalEditor_C::Image_9' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_10) == 0x0004F0, "Member 'UWBP_PalEditor_C::Image_10' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_11) == 0x0004F8, "Member 'UWBP_PalEditor_C::Image_11' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_12) == 0x000500, "Member 'UWBP_PalEditor_C::Image_12' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_13) == 0x000508, "Member 'UWBP_PalEditor_C::Image_13' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_14) == 0x000510, "Member 'UWBP_PalEditor_C::Image_14' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_15) == 0x000518, "Member 'UWBP_PalEditor_C::Image_15' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_16) == 0x000520, "Member 'UWBP_PalEditor_C::Image_16' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Image_64) == 0x000528, "Member 'UWBP_PalEditor_C::Image_64' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, MaxHPText) == 0x000530, "Member 'UWBP_PalEditor_C::MaxHPText' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, PassiveContainer) == 0x000538, "Member 'UWBP_PalEditor_C::PassiveContainer' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, ShuffleIcon) == 0x000540, "Member 'UWBP_PalEditor_C::ShuffleIcon' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, ShuffleIcon_1) == 0x000548, "Member 'UWBP_PalEditor_C::ShuffleIcon_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox) == 0x000550, "Member 'UWBP_PalEditor_C::SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_1) == 0x000558, "Member 'UWBP_PalEditor_C::SpinBox_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_2) == 0x000560, "Member 'UWBP_PalEditor_C::SpinBox_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_3) == 0x000568, "Member 'UWBP_PalEditor_C::SpinBox_3' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_4) == 0x000570, "Member 'UWBP_PalEditor_C::SpinBox_4' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_5) == 0x000578, "Member 'UWBP_PalEditor_C::SpinBox_5' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_6) == 0x000580, "Member 'UWBP_PalEditor_C::SpinBox_6' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_7) == 0x000588, "Member 'UWBP_PalEditor_C::SpinBox_7' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_8) == 0x000590, "Member 'UWBP_PalEditor_C::SpinBox_8' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_9) == 0x000598, "Member 'UWBP_PalEditor_C::SpinBox_9' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_10) == 0x0005A0, "Member 'UWBP_PalEditor_C::SpinBox_10' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_13) == 0x0005A8, "Member 'UWBP_PalEditor_C::SpinBox_13' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_14) == 0x0005B0, "Member 'UWBP_PalEditor_C::SpinBox_14' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_15) == 0x0005B8, "Member 'UWBP_PalEditor_C::SpinBox_15' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_16) == 0x0005C0, "Member 'UWBP_PalEditor_C::SpinBox_16' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SpinBox_147) == 0x0005C8, "Member 'UWBP_PalEditor_C::SpinBox_147' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, TemplateList) == 0x0005D0, "Member 'UWBP_PalEditor_C::TemplateList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, TemplateWindow) == 0x0005D8, "Member 'UWBP_PalEditor_C::TemplateWindow' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, TemplateWindowInner) == 0x0005E0, "Member 'UWBP_PalEditor_C::TemplateWindowInner' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, UpgradesContainer) == 0x0005E8, "Member 'UWBP_PalEditor_C::UpgradesContainer' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WazaAvailableList) == 0x0005F0, "Member 'UWBP_PalEditor_C::WazaAvailableList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WazaAvailablePage) == 0x0005F8, "Member 'UWBP_PalEditor_C::WazaAvailablePage' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WazaMasteredList) == 0x000600, "Member 'UWBP_PalEditor_C::WazaMasteredList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WazaMasteredPage) == 0x000608, "Member 'UWBP_PalEditor_C::WazaMasteredPage' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_ActiveSkill) == 0x000610, "Member 'UWBP_PalEditor_C::WBP_ActiveSkill' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_ActiveSkill_1) == 0x000618, "Member 'UWBP_PalEditor_C::WBP_ActiveSkill_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_ActiveSkill_2) == 0x000620, "Member 'UWBP_PalEditor_C::WBP_ActiveSkill_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button) == 0x000628, "Member 'UWBP_PalEditor_C::WBP_Button' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_1) == 0x000630, "Member 'UWBP_PalEditor_C::WBP_Button_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_2) == 0x000638, "Member 'UWBP_PalEditor_C::WBP_Button_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_3) == 0x000640, "Member 'UWBP_PalEditor_C::WBP_Button_3' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_4) == 0x000648, "Member 'UWBP_PalEditor_C::WBP_Button_4' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_5) == 0x000650, "Member 'UWBP_PalEditor_C::WBP_Button_5' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_6) == 0x000658, "Member 'UWBP_PalEditor_C::WBP_Button_6' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_7) == 0x000660, "Member 'UWBP_PalEditor_C::WBP_Button_7' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_8) == 0x000668, "Member 'UWBP_PalEditor_C::WBP_Button_8' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_11) == 0x000670, "Member 'UWBP_PalEditor_C::WBP_Button_11' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Button_299) == 0x000678, "Member 'UWBP_PalEditor_C::WBP_Button_299' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_PalCharacterInfo) == 0x000680, "Member 'UWBP_PalEditor_C::WBP_PalCharacterInfo' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_PassiveList_101) == 0x000688, "Member 'UWBP_PalEditor_C::WBP_PassiveList_101' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_PassiveSkill) == 0x000690, "Member 'UWBP_PalEditor_C::WBP_PassiveSkill' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_PassiveSkill_1) == 0x000698, "Member 'UWBP_PalEditor_C::WBP_PassiveSkill_1' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_PassiveSkill_2) == 0x0006A0, "Member 'UWBP_PalEditor_C::WBP_PassiveSkill_2' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_PassiveSkill_3) == 0x0006A8, "Member 'UWBP_PalEditor_C::WBP_PassiveSkill_3' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WBP_Tooltip) == 0x0006B0, "Member 'UWBP_PalEditor_C::WBP_Tooltip' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WidgetSwitcher_1001) == 0x0006B8, "Member 'UWBP_PalEditor_C::WidgetSwitcher_1001' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, CharacterParams) == 0x0006C0, "Member 'UWBP_PalEditor_C::CharacterParams' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SelectedID) == 0x000980, "Member 'UWBP_PalEditor_C::SelectedID' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SelectedName) == 0x000988, "Member 'UWBP_PalEditor_C::SelectedName' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, OnFinish) == 0x0009A0, "Member 'UWBP_PalEditor_C::OnFinish' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, CurrentlySelectedPassiveSlot) == 0x0009B0, "Member 'UWBP_PalEditor_C::CurrentlySelectedPassiveSlot' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, Gender) == 0x0009B8, "Member 'UWBP_PalEditor_C::Gender' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, WazaList) == 0x0009C0, "Member 'UWBP_PalEditor_C::WazaList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, PassiveList) == 0x0009C8, "Member 'UWBP_PalEditor_C::PassiveList' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, bAllowUniqueAbilitiesOnAnyone) == 0x0009D0, "Member 'UWBP_PalEditor_C::bAllowUniqueAbilitiesOnAnyone' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, HistoryComponent) == 0x0009D8, "Member 'UWBP_PalEditor_C::HistoryComponent' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, CurrentParams) == 0x0009E0, "Member 'UWBP_PalEditor_C::CurrentParams' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, PassiveSlots) == 0x000CA0, "Member 'UWBP_PalEditor_C::PassiveSlots' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, ActiveSkillSlots) == 0x000CB0, "Member 'UWBP_PalEditor_C::ActiveSkillSlots' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, bDisableEvents) == 0x000CC0, "Member 'UWBP_PalEditor_C::bDisableEvents' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, bIsTooltipVisible) == 0x000CC1, "Member 'UWBP_PalEditor_C::bIsTooltipVisible' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, EscapeHandle) == 0x000CC4, "Member 'UWBP_PalEditor_C::EscapeHandle' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, ModVersion) == 0x000CC8, "Member 'UWBP_PalEditor_C::ModVersion' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SaveObject) == 0x000CD8, "Member 'UWBP_PalEditor_C::SaveObject' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, AllWazaDataArray) == 0x000CE0, "Member 'UWBP_PalEditor_C::AllWazaDataArray' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, AllWazaDataMap) == 0x000CF0, "Member 'UWBP_PalEditor_C::AllWazaDataMap' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, AvailableWazaDataArray) == 0x000D40, "Member 'UWBP_PalEditor_C::AvailableWazaDataArray' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, MasteredWazaDataArray) == 0x000D50, "Member 'UWBP_PalEditor_C::MasteredWazaDataArray' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, EquippedWazaDataArray) == 0x000D60, "Member 'UWBP_PalEditor_C::EquippedWazaDataArray' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, SelectedActiveSkillSlot) == 0x000D70, "Member 'UWBP_PalEditor_C::SelectedActiveSkillSlot' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, CurrentActiveSkillIndex) == 0x000D78, "Member 'UWBP_PalEditor_C::CurrentActiveSkillIndex' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, bIsHealthOverflowing) == 0x000D7C, "Member 'UWBP_PalEditor_C::bIsHealthOverflowing' has a wrong offset!");
static_assert(offsetof(UWBP_PalEditor_C, bShouldObtainAsEgg) == 0x000D7D, "Member 'UWBP_PalEditor_C::bShouldObtainAsEgg' has a wrong offset!");

}

