#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalWazaList

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function WBP_PalWazaList.WBP_PalWazaList_C.Refresh
// 0x0130 (0x0130 - 0x0000)
struct WBP_PalWazaList_C_Refresh final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B6B[0x4];                                     // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalWazaDatabase*                       CallFunc_GetWazaDatabase_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMap<EPalWazaID, int32>                       CallFunc_GetMasterrableWaza_BetweenLevel_OutMap;   // 0x0018(0x0050)()
	TDelegate<void(bool bIsLearned, class UWBP_WazaButton_C* WazaElement)> K2Node_CreateDelegate_OutputDelegate;              // 0x0068(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_WazaButton_C*                      CallFunc_Create_ReturnValue;                       // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalGameInstance*                       CallFunc_GetPalGameInstance_ReturnValue;           // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetDataTableRowNames_OutRowNames;         // 0x0088(0x0010)(ReferenceParm)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B6C[0x3];                                     // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalWazaDatabaseRaw                    CallFunc_GetDataTableRowFromName_OutRow;           // 0x00B0(0x0050)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B6D[0x3];                                     // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Map_Find_Value;                           // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B6E[0x3];                                     // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B6F[0x7];                                     // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetWazaName_outName;                      // 0x0118(0x0018)()
};
static_assert(alignof(WBP_PalWazaList_C_Refresh) == 0x000008, "Wrong alignment on WBP_PalWazaList_C_Refresh");
static_assert(sizeof(WBP_PalWazaList_C_Refresh) == 0x000130, "Wrong size on WBP_PalWazaList_C_Refresh");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'WBP_PalWazaList_C_Refresh::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, Temp_int_Array_Index_Variable) == 0x000004, "Member 'WBP_PalWazaList_C_Refresh::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetWazaDatabase_ReturnValue) == 0x000010, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetWazaDatabase_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetMasterrableWaza_BetweenLevel_OutMap) == 0x000018, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetMasterrableWaza_BetweenLevel_OutMap' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, K2Node_CreateDelegate_OutputDelegate) == 0x000068, "Member 'WBP_PalWazaList_C_Refresh::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Create_ReturnValue) == 0x000078, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetPalGameInstance_ReturnValue) == 0x000080, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetPalGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetDataTableRowNames_OutRowNames) == 0x000088, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetDataTableRowNames_OutRowNames' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_AddChild_ReturnValue) == 0x000098, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Array_Get_Item) == 0x0000A0, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Array_Length_ReturnValue) == 0x0000A8, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Less_IntInt_ReturnValue) == 0x0000AC, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetDataTableRowFromName_OutRow) == 0x0000B0, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000100, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Map_Find_Value) == 0x000104, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Map_Find_ReturnValue) == 0x000108, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Array_Add_ReturnValue) == 0x00010C, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_Array_Contains_ReturnValue) == 0x000110, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_Refresh, CallFunc_GetWazaName_outName) == 0x000118, "Member 'WBP_PalWazaList_C_Refresh::CallFunc_GetWazaName_outName' has a wrong offset!");

// Function WBP_PalWazaList.WBP_PalWazaList_C.OnWazaStateChanged
// 0x0010 (0x0010 - 0x0000)
struct WBP_PalWazaList_C_OnWazaStateChanged final
{
public:
	bool                                          bIsLearned;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B70[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_WazaButton_C*                      WazaElement;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalWazaList_C_OnWazaStateChanged) == 0x000008, "Wrong alignment on WBP_PalWazaList_C_OnWazaStateChanged");
static_assert(sizeof(WBP_PalWazaList_C_OnWazaStateChanged) == 0x000010, "Wrong size on WBP_PalWazaList_C_OnWazaStateChanged");
static_assert(offsetof(WBP_PalWazaList_C_OnWazaStateChanged, bIsLearned) == 0x000000, "Member 'WBP_PalWazaList_C_OnWazaStateChanged::bIsLearned' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_OnWazaStateChanged, WazaElement) == 0x000008, "Member 'WBP_PalWazaList_C_OnWazaStateChanged::WazaElement' has a wrong offset!");

// Function WBP_PalWazaList.WBP_PalWazaList_C.OnWazaRemoved_Delegate__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature final
{
public:
	EPalWazaID                                    WazaID;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature) == 0x000001, "Wrong alignment on WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature");
static_assert(sizeof(WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature) == 0x000001, "Wrong size on WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature");
static_assert(offsetof(WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature, WazaID) == 0x000000, "Member 'WBP_PalWazaList_C_OnWazaRemoved_Delegate__DelegateSignature::WazaID' has a wrong offset!");

// Function WBP_PalWazaList.WBP_PalWazaList_C.OnWazaAdded_Delegate__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature final
{
public:
	EPalWazaID                                    WazaID;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature) == 0x000001, "Wrong alignment on WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature");
static_assert(sizeof(WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature) == 0x000001, "Wrong size on WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature");
static_assert(offsetof(WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature, WazaID) == 0x000000, "Member 'WBP_PalWazaList_C_OnWazaAdded_Delegate__DelegateSignature::WazaID' has a wrong offset!");

// Function WBP_PalWazaList.WBP_PalWazaList_C.ExecuteUbergraph_WBP_PalWazaList
// 0x0080 (0x0080 - 0x0000)
struct WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0008(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B71[0x3];                                     // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B72[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue_1;             // 0x0040(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWBP_WazaButton_C*                      K2Node_DynamicCast_AsWBP_Waza_Button;              // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B73[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item_1;                         // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_WazaButton_C*                      K2Node_DynamicCast_AsWBP_Waza_Button_1;            // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B74[0x3];                                     // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList) == 0x000008, "Wrong alignment on WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList");
static_assert(sizeof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList) == 0x000080, "Wrong size on WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, EntryPoint) == 0x000000, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_GetAllChildren_ReturnValue) == 0x000008, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Array_Length_ReturnValue) == 0x00001C, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, Temp_int_Array_Index_Variable) == 0x000020, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, Temp_int_Loop_Counter_Variable_1) == 0x000024, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Add_IntInt_ReturnValue_1) == 0x00002C, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, Temp_int_Array_Index_Variable_1) == 0x000030, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Array_Get_Item) == 0x000038, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_GetAllChildren_ReturnValue_1) == 0x000040, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_GetAllChildren_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, K2Node_DynamicCast_AsWBP_Waza_Button) == 0x000050, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::K2Node_DynamicCast_AsWBP_Waza_Button' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Array_Get_Item_1) == 0x000060, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, K2Node_DynamicCast_AsWBP_Waza_Button_1) == 0x000068, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::K2Node_DynamicCast_AsWBP_Waza_Button_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, K2Node_DynamicCast_bSuccess_1) == 0x000070, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Array_Length_ReturnValue_1) == 0x000074, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList, CallFunc_Less_IntInt_ReturnValue_1) == 0x000078, "Member 'WBP_PalWazaList_C_ExecuteUbergraph_WBP_PalWazaList::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");

}

